FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY src/backend ./src/backend
RUN dotnet restore src/backend/GameCore.sln
RUN dotnet publish src/backend/GameCore.WebAPI/GameCore.WebAPI.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet","GameCore.WebAPI.dll"]
